# Generated by Django 5.0.6 on 2024-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_jins_user_manzil_user_middle_name_user_rasm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='+998907791449', max_length=14),
            preserve_default=False,
        ),
    ]
