# Generated by Django 5.0.6 on 2024-05-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular')], default='Regular', max_length=50),
        ),
    ]
